title: StackCrafted
description: Self-Hosting & Docker Tutorials.
baseurl: ""
url: "https://stackcrafted.org"

theme: jekyll-theme-hacker

plugins:
  - jekyll-seo-tag

markdown: kramdown

permalink: pretty
# Enable copy button on code blocks
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Enable copy button
plugins:
  - jekyll-feed

# Copy button styling
enable_copy_code_button: true


