title: StackCrafted
description: Docker & self-hosting tutorials, done properly.
baseurl: ""
url: "https://stackcrafted.org"

theme: jekyll-theme-hacker

plugins:
  - jekyll-seo-tag

markdown: kramdown

permalink: pretty

