title: StackCrafted
description: Self-Hosting & Docker Tutorials.
baseurl: ""
url: "https://stackcrafted.org"

theme: jekyll-theme-hacker

plugins:
  - jekyll-seo-tag

markdown: kramdown

permalink: pretty

